# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        blog_db_provider:
            entity:
                class: BlogBlogBundle:User
                property: userName

        in_memory:
            memory: ~

    encoders:
        Blog\BlogBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
            ROLE_AUTHOR:        ROLE_USER
            ROLE_ADMIN:       [ROLE_USER, ROLE_AUTHOR]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            logout: true
#            pattern:    ^/
#            http_basic: ~
            provider: blog_db_provider
            form_login:
                check_path: /login
                login_path: /login
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /login


#

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: /register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: /add, roles: ROLE_AUTHOR}
        - { path: /admin, roles: ROLE_ADMIN }
        - { path: /, roles: IS_AUTHENTICATED_FULLY}
